#!/bin/bash
# Usage: script/e2etest
# Runs the projects integration tests.

set -e errexit

HTTP_PORT=8000
ls
./script/lib/server.js --port=$HTTP_PORT --root ./client &
HTTP_PORT=$HTTP_PORT ./node_modules/.bin/protractor config/protractor.config.js
