#!/bin/bash
# Usage: script/test
# Runs the projects test suite.

set -e errexit

./node_modules/.bin/karma start ./config/karma.config.js --single-run

sh ./script/e2etest

sh ./script/ensure-no-ddescribe

./node_modules/.bin/jshint .
